version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10
    steps:
      - add_ssh_keys:
          fingerprints:
            - "8d:03:f0:aa:d7:9a:4e:37:cb:bc:b7:da:f4:1c:91:4a"
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run: npm run build
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}